import {
  StudentRecord,
  TeacherRecord,
  CourseRecord,
  AttendanceRecord,
  AssignmentRecord,
  ResultRecord,
  NoticeRecord,
  CampusEvent,
  AcademicResource,
  ShuttleBusRoute,
  LostFoundItem,
  ComplaintTicket
} from './types';

export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: 1,
    userId: 275105101119,
    studentId: 'CU-2023-CSE-042',
    fullName: 'Md Arifuzzaman Abir',
    email: 'abir.cse@cityuniversity.edu.bd',
    department: 'Computer Science & Engineering',
    semester: 4,
    batch: 'Batch 66',
    cgpa: 3.41,
    phone: '+8801735355846',
    enrollmentStatus: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 2,
    userId: 102,
    studentId: 'CU-2023-CSE-045',
    fullName: 'Nusrat Jahan',
    email: 'nusrat.cse@cityuniversity.edu.bd',
    department: 'Computer Science & Engineering',
    semester: 5,
    batch: 'Batch 58',
    cgpa: 3.92,
    phone: '+880 1819-876543',
    enrollmentStatus: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 3,
    userId: 103,
    studentId: 'CU-2024-EEE-012',
    fullName: 'Tanvir Hasan',
    email: 'tanvir.eee@cityuniversity.edu.bd',
    department: 'Electrical & Electronic Engineering',
    semester: 3,
    batch: 'Batch 60',
    cgpa: 3.65,
    phone: '+880 1912-345678',
    enrollmentStatus: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 4,
    userId: 104,
    studentId: 'CU-2022-BBA-088',
    fullName: 'Sadia Sultana',
    email: 'sadia.bba@cityuniversity.edu.bd',
    department: 'Business Administration',
    semester: 7,
    batch: 'Batch 56',
    cgpa: 3.78,
    phone: '+880 1623-456789',
    enrollmentStatus: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 5,
    userId: 105,
    studentId: 'CU-2023-CSE-099',
    fullName: 'Mahir Faisal',
    email: 'mahir.cse@cityuniversity.edu.bd',
    department: 'Computer Science & Engineering',
    semester: 5,
    batch: 'Batch 58',
    cgpa: 3.42,
    phone: '+880 1534-567890',
    enrollmentStatus: 'active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  }
];

export const INITIAL_TEACHERS: TeacherRecord[] = [
  {
    id: 1,
    userId: 201,
    teacherId: 'CU-FAC-019',
    fullName: 'Dr. Selim Reza',
    email: 'selim.reza@cityuniversity.edu.bd',
    department: 'Computer Science & Engineering',
    designation: 'Associate Professor & Head of Dept',
    officeRoom: 'Bldg 2, Room 402',
    specialization: 'Distributed Systems & Database Architectures',
    phone: '+880 1712-000111',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 2,
    userId: 202,
    teacherId: 'CU-FAC-034',
    fullName: 'Prof. Farhana Ahmed',
    email: 'farhana.ahmed@cityuniversity.edu.bd',
    department: 'Computer Science & Engineering',
    designation: 'Assistant Professor',
    officeRoom: 'Bldg 2, Room 415',
    specialization: 'Artificial Intelligence, Algorithms & Complexity',
    phone: '+880 1819-222333',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 3,
    userId: 203,
    teacherId: 'CU-FAC-052',
    fullName: 'Engr. Kazi Mizanur',
    email: 'mizanur.eee@cityuniversity.edu.bd',
    department: 'Electrical & Electronic Engineering',
    designation: 'Senior Lecturer',
    officeRoom: 'Bldg 3, Room 208',
    specialization: 'Power Electronics & Embedded Systems',
    phone: '+880 1911-444555',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
  }
];

export const INITIAL_COURSES: CourseRecord[] = [
  {
    id: 1,
    courseCode: 'CSE-3101',
    title: 'Algorithms & Complexity Analysis',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    semester: 5,
    teacherId: 2,
    teacherName: 'Prof. Farhana Ahmed',
    description: 'Graph algorithms, dynamic programming, NP-completeness, divide & conquer methodologies.',
    schedule: 'Sun & Tue: 10:00 AM - 11:30 AM',
    room: 'Academic Lab 401',
    enrolledStudentsCount: 48,
  },
  {
    id: 2,
    courseCode: 'CSE-3103',
    title: 'Database Management Systems',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    semester: 5,
    teacherId: 1,
    teacherName: 'Dr. Selim Reza',
    description: 'Relational model, PostgreSQL, indexing, transaction processing, ACID compliance, normalization.',
    schedule: 'Mon & Wed: 11:30 AM - 01:00 PM',
    room: 'Seminar Hall B',
    enrolledStudentsCount: 52,
  },
  {
    id: 3,
    courseCode: 'CSE-3105',
    title: 'Web Application & API Engineering',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    semester: 5,
    teacherId: 2,
    teacherName: 'Prof. Farhana Ahmed',
    description: 'REST architecture, FastAPI, React, modern web standards, state management and deployment.',
    schedule: 'Mon & Wed: 02:00 PM - 03:30 PM',
    room: 'Software Lab 3',
    enrolledStudentsCount: 45,
  },
  {
    id: 4,
    courseCode: 'EEE-2101',
    title: 'Signals & Linear Systems',
    creditHours: 3.0,
    department: 'Electrical & Electronic Engineering',
    semester: 3,
    teacherId: 3,
    teacherName: 'Engr. Kazi Mizanur',
    description: 'Fourier series, Laplace transforms, convolution, filters and time-domain analysis.',
    schedule: 'Sun & Tue: 08:30 AM - 10:00 AM',
    room: 'Bldg 3, Room 102',
    enrolledStudentsCount: 36,
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 1,
    courseId: 1,
    courseCode: 'CSE-3101',
    courseTitle: 'Algorithms & Complexity Analysis',
    studentId: 1,
    studentName: 'Rafid Ahmed',
    studentRoll: 'CU-2023-CSE-042',
    date: '2026-10-06',
    status: 'present',
    verificationMethod: 'qr_scan',
    timestamp: '10:02 AM',
  },
  {
    id: 2,
    courseId: 1,
    courseCode: 'CSE-3101',
    courseTitle: 'Algorithms & Complexity Analysis',
    studentId: 2,
    studentName: 'Nusrat Jahan',
    studentRoll: 'CU-2023-CSE-045',
    date: '2026-10-06',
    status: 'present',
    verificationMethod: 'qr_scan',
    timestamp: '09:58 AM',
  },
  {
    id: 3,
    courseId: 2,
    courseCode: 'CSE-3103',
    courseTitle: 'Database Management Systems',
    studentId: 1,
    studentName: 'Rafid Ahmed',
    studentRoll: 'CU-2023-CSE-042',
    date: '2026-10-07',
    status: 'present',
    verificationMethod: 'qr_scan',
    timestamp: '11:31 AM',
  },
  {
    id: 4,
    courseId: 2,
    courseCode: 'CSE-3103',
    courseTitle: 'Database Management Systems',
    studentId: 5,
    studentName: 'Mahir Faisal',
    studentRoll: 'CU-2023-CSE-099',
    date: '2026-10-07',
    status: 'late',
    verificationMethod: 'manual',
    timestamp: '11:48 AM',
  }
];

export const INITIAL_ASSIGNMENTS: AssignmentRecord[] = [
  {
    id: 1,
    courseId: 1,
    courseCode: 'CSE-3101',
    courseTitle: 'Algorithms & Complexity Analysis',
    title: 'Assignment 2: Dijkstra & A* Pathfinding Benchmark',
    description: 'Implement shortest path algorithms in Python and benchmark performance against large sparse graphs. Submit source code and runtime chart.',
    dueDate: '2026-10-15T23:59:00',
    maxMarks: 100,
    status: 'pending',
  },
  {
    id: 2,
    courseId: 2,
    courseCode: 'CSE-3103',
    courseTitle: 'Database Management Systems',
    title: 'Project Milestone 1: PostgreSQL Schema & Normalization',
    description: 'Design 3NF relational schema with foreign key constraints, B-tree indexes, and trigger functions for City University CampusOS.',
    dueDate: '2026-10-18T23:59:00',
    maxMarks: 50,
    status: 'submitted',
    submittedDate: '2026-10-07T14:30:00',
  },
  {
    id: 3,
    courseId: 3,
    courseCode: 'CSE-3105',
    courseTitle: 'Web Application & API Engineering',
    title: 'Lab Task 4: JWT Authentication Middleware',
    description: 'Build secure token exchange and password hashing with bcrypt in FastAPI / Express.',
    dueDate: '2026-10-05T23:59:00',
    maxMarks: 30,
    status: 'graded',
    submittedDate: '2026-10-04T18:00:00',
    marksObtained: 29,
    feedback: 'Excellent modular structure and proper HTTP 401 handling.',
  }
];

export const INITIAL_RESULTS: ResultRecord[] = [
  {
    id: 1,
    studentId: 1,
    courseId: 1,
    courseCode: 'CSE-3101',
    courseTitle: 'Algorithms & Complexity Analysis',
    creditHours: 3.0,
    semester: 5,
    midtermMarks: 28,
    finalMarks: 45,
    assignmentMarks: 15,
    attendanceMarks: 10,
    totalMarks: 98,
    grade: 'A+',
    gradePoint: 4.00,
  },
  {
    id: 2,
    studentId: 1,
    courseId: 2,
    courseCode: 'CSE-3103',
    courseTitle: 'Database Management Systems',
    creditHours: 3.0,
    semester: 5,
    midtermMarks: 26,
    finalMarks: 42,
    assignmentMarks: 14,
    attendanceMarks: 10,
    totalMarks: 92,
    grade: 'A',
    gradePoint: 3.75,
  },
  {
    id: 3,
    studentId: 1,
    courseId: 3,
    courseCode: 'CSE-3105',
    courseTitle: 'Web Application & API Engineering',
    creditHours: 3.0,
    semester: 5,
    midtermMarks: 29,
    finalMarks: 47,
    assignmentMarks: 15,
    attendanceMarks: 10,
    totalMarks: 101,
    grade: 'A+',
    gradePoint: 4.00,
  }
];

export const INITIAL_NOTICES: NoticeRecord[] = [
  {
    id: 1,
    title: 'CPCCU Hackathon 2026: CampusOS Grand Finale Scheduled',
    content: 'All participants of the AI-Powered Web App Development Hackathon must submit project links and conduct live QR verification at Seminar Room 3.',
    category: 'clubs',
    priority: 'urgent',
    author: 'Competitive Programming Camp CU',
    isPinned: true,
    publishedAt: '2026-10-08 09:00 AM',
  },
  {
    id: 2,
    title: 'Midterm Examination Schedule for Fall 2026 Published',
    content: 'Exam routine for CSE, EEE, and BBA departments has been officially published. Please collect your admit cards from department accounts by Oct 20.',
    category: 'exam',
    priority: 'high',
    author: 'Office of Controller of Examinations',
    isPinned: true,
    publishedAt: '2026-10-07 02:30 PM',
  },
  {
    id: 3,
    title: 'Shuttle Bus Route 3 (Mirpur-10) Timing Adjustment',
    content: 'Starting Sunday, Morning Shuttle #3 will depart Mirpur-10 round-about at 07:15 AM sharp due to ongoing metro rail expansion roadworks.',
    category: 'bus',
    priority: 'normal',
    author: 'CU Transport Division',
    isPinned: false,
    publishedAt: '2026-10-06 05:00 PM',
  },
  {
    id: 4,
    title: 'Class Rescheduled: CSE-3103 Database Lab Room Shift',
    content: 'Prof. Selim Reza informs that Wednesday 11:30 AM class is shifted to Central Software Lab 2 on Level 4.',
    category: 'academic',
    priority: 'high',
    author: 'CSE Department Notice Desk',
    isPinned: false,
    publishedAt: '2026-10-05 10:15 AM',
  }
];

export const INITIAL_EVENTS: CampusEvent[] = [
  {
    id: 1,
    title: 'CPCCU AI-Powered Hackathon 2026',
    clubName: 'Competitive Programming Camp CU',
    clubCategory: 'technical',
    date: 'Oct 12, 2026',
    time: '09:00 AM - 08:00 PM',
    location: 'Auditorium & Innovation Hub',
    description: '24-hour sprint building real campus solutions for City University. Cash pool of 50,000 BDT + mentorship from industry leads.',
    bannerUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80',
    capacity: 120,
    registeredCount: 88,
    isRegistered: true,
    ticketCode: 'CPCCU-HACK-2026-TKT-8842',
  },
  {
    id: 2,
    title: 'Robotics Workshop: Autonomous Rovers with ROS2',
    clubName: 'CU Robotics & Mechatronics Society',
    clubCategory: 'technical',
    date: 'Oct 16, 2026',
    time: '02:30 PM - 05:30 PM',
    location: 'Hardware Lab 3, Level 2',
    description: 'Hands-on hardware session with LiDAR sensors, microcontroller serial telemetry, and obstacle avoidance algorithms.',
    bannerUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    capacity: 40,
    registeredCount: 32,
    isRegistered: false,
  },
  {
    id: 3,
    title: 'Intra-University Parliamentary Debate Championship',
    clubName: 'City University Debating Club',
    clubCategory: 'debate',
    date: 'Oct 22, 2026',
    time: '10:00 AM - 06:00 PM',
    location: 'Conference Hall A',
    description: 'Annual flagship debate tournament covering national tech policies, academic reforms, and global economics.',
    bannerUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    capacity: 80,
    registeredCount: 65,
    isRegistered: false,
  },
  {
    id: 4,
    title: 'Inter-Department Futsal Super Cup 2026',
    clubName: 'CU Sports Club',
    clubCategory: 'sports',
    date: 'Oct 28, 2026',
    time: '03:00 PM - 07:00 PM',
    location: 'Campus Sports Ground',
    description: '16 teams representing CSE, EEE, Civil, BBA, Law and English. Knockout tournament with live commentary.',
    bannerUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    capacity: 200,
    registeredCount: 145,
    isRegistered: false,
  }
];

export const INITIAL_RESOURCES: AcademicResource[] = [
  {
    id: 1,
    title: 'CSE-3101 Midterm Examination Question Paper (Fall 2024)',
    courseCode: 'CSE-3101',
    courseName: 'Algorithms & Complexity Analysis',
    department: 'Computer Science & Engineering',
    semester: 5,
    category: 'question_paper',
    uploadedBy: 'Nusrat Jahan (CR)',
    uploadDate: '2026-09-20',
    fileSize: '1.8 MB',
    fileType: 'PDF',
    downloadsCount: 142,
  },
  {
    id: 2,
    title: 'CSE-3103 Complete PostgreSQL & Indexing Lecture Notes',
    courseCode: 'CSE-3103',
    courseName: 'Database Management Systems',
    department: 'Computer Science & Engineering',
    semester: 5,
    category: 'lecture_notes',
    uploadedBy: 'Dr. Selim Reza (Faculty)',
    uploadDate: '2026-10-01',
    fileSize: '4.2 MB',
    fileType: 'PDF',
    downloadsCount: 219,
  },
  {
    id: 3,
    title: 'CSE-3105 RESTful API Design & Postman Collection',
    courseCode: 'CSE-3105',
    courseName: 'Web Application & API Engineering',
    department: 'Computer Science & Engineering',
    semester: 5,
    category: 'lab_manual',
    uploadedBy: 'Prof. Farhana Ahmed',
    uploadDate: '2026-10-03',
    fileSize: '3.1 MB',
    fileType: 'ZIP',
    downloadsCount: 97,
  },
  {
    id: 4,
    title: 'EEE-2101 Signals & Linear Systems Solved Question Bank',
    courseCode: 'EEE-2101',
    courseName: 'Signals & Linear Systems',
    department: 'Electrical & Electronic Engineering',
    semester: 3,
    category: 'solution',
    uploadedBy: 'Tanvir Hasan',
    uploadDate: '2026-09-15',
    fileSize: '6.4 MB',
    fileType: 'PDF',
    downloadsCount: 168,
  }
];

export const INITIAL_BUS_ROUTES: ShuttleBusRoute[] = [
  {
    id: 'route-1',
    routeName: 'Route 1: Mirpur - Campus Express',
    busNumber: 'CU Shuttle #01 (Dhaka Metro-Ga 11-4502)',
    startingPoint: 'Mirpur-10 Roundabout',
    destination: 'City University Permanent Campus',
    stops: ['Mirpur-10', 'Mirpur-14', 'ECB Chattar', 'Kalshi', 'Beribadh Highway', 'Campus Main Gate'],
    scheduleTimes: ['07:15 AM', '08:30 AM', '11:00 AM', '01:30 PM', '04:30 PM', '06:00 PM'],
    currentStatus: 'on_time',
    driverContact: '+880 1715-998811 (Md. Jalal Uddin)',
  },
  {
    id: 'route-2',
    routeName: 'Route 2: Uttara - Airport Connector',
    busNumber: 'CU Shuttle #02 (Dhaka Metro-Ga 12-8921)',
    startingPoint: 'Uttara House Building (Sector 7)',
    destination: 'City University Permanent Campus',
    stops: ['House Building', 'Azampur', 'Jasmin Mor', 'Abdullahpur', 'Ashulia Bridge', 'Campus Main Gate'],
    scheduleTimes: ['07:20 AM', '08:45 AM', '12:15 PM', '02:00 PM', '05:15 PM'],
    currentStatus: 'in_transit',
    driverContact: '+880 1812-443322 (Md. Rafique Mia)',
  },
  {
    id: 'route-3',
    routeName: 'Route 3: Dhanmondi - Farmgate Route',
    busNumber: 'CU Shuttle #03 (Dhaka Metro-Ga 14-3310)',
    startingPoint: 'Dhanmondi 32 / Shukrabad',
    destination: 'City University Permanent Campus',
    stops: ['Dhanmondi 32', 'Farmgate Ananda Hall', 'Bijoy Sarani', 'Khamarbari', 'Agargaon', 'Campus Main Gate'],
    scheduleTimes: ['07:00 AM', '08:15 AM', '01:15 PM', '04:45 PM'],
    currentStatus: 'on_time',
    driverContact: '+880 1913-776655 (Md. Alamgir Hossain)',
  }
];

export const INITIAL_LOST_FOUND: LostFoundItem[] = [
  {
    id: 1,
    type: 'lost',
    title: 'Casio fx-991EX Scientific Calculator',
    category: 'calculator',
    location: 'Academic Bldg 2, Room 401 (Near 3rd row)',
    dateReported: '2026-10-07',
    contactName: 'Tanvir Hasan (EEE-3rd)',
    contactPhone: '+880 1912-345678',
    description: 'Black body with silver keypad, has a small CPCCU sticker on the back cover.',
    status: 'open',
  },
  {
    id: 2,
    type: 'found',
    title: 'City University Student ID Card (CU-2024-BBA-112)',
    category: 'id_card',
    location: 'Canteen Cash Counter',
    dateReported: '2026-10-08',
    contactName: 'Canteen Supervisor (Uncle Rafiq)',
    contactPhone: '+880 1711-009988',
    description: 'Name on card is "Farhan Kabir". Card kept securely at the canteen counter.',
    status: 'open',
  },
  {
    id: 3,
    type: 'lost',
    title: 'Dell 65W Type-C Laptop Charger',
    category: 'electronics',
    location: 'Central Library Silent Study Area (Table 14)',
    dateReported: '2026-10-06',
    contactName: 'Rafid Ahmed',
    contactPhone: '+880 1711-234567',
    description: 'Original black Dell brick with 3-pin cable. Left during library closing hours.',
    status: 'open',
  }
];

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: 'CU-CMP-2026-081',
    title: 'AC unit in Academic Bldg 2 Room 402 leaking water',
    department: 'Engineering & Estate Maintenance',
    category: 'infrastructure',
    description: 'The split AC unit on the north wall is dripping water directly over student desks during afternoon lectures.',
    submittedAt: '2026-10-06 11:20 AM',
    status: 'in_review',
    feedbackNotes: 'Technician assigned. Inspection scheduled for Thursday 4 PM.',
  },
  {
    id: 'CU-CMP-2026-079',
    title: 'Overcrowding on 08:30 AM Mirpur Shuttle Bus',
    department: 'Transport Division',
    category: 'bus_service',
    description: 'Demand exceeds seating capacity by over 20 students at ECB Chattar stop. Requesting an additional bus at 08:15 AM.',
    submittedAt: '2026-10-04 09:10 AM',
    status: 'received',
    feedbackNotes: 'Transport Committee reviewing passenger counts for route expansion.',
  }
];
